import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';
import { injectGoEntry } from '../inject.js';

export function generateTuiGlue(tuiDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(tuiDir, 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  const serverNames = Object.keys(plugin.mcpServers);
  for (const serverName of serverNames) {
    const fileName = `plugin_${serverName}.go`;
    const filePath = join(glueDir, fileName);
    writeFileSync(filePath, generatePluginTab(serverName, plugin), 'utf-8');
    files.push(`plugin-glue/${fileName}`);
  }

  if (serverNames.length === 0) return files;

  // The per-server files are not a stable injection target — their names change
  // with the plugin's MCP server list, so wiring them into main.go one by one
  // would duplicate or rot on re-run. This aggregator is the stable symbol the
  // entry point calls, which is what makes the injection idempotent.
  writeFileSync(join(glueDir, 'plugins.go'), generateAggregator(serverNames, plugin), 'utf-8');
  files.push('plugin-glue/plugins.go');

  wireTuiEntry(tuiDir);

  return files;
}

/** Wire the aggregator into the TUI entry point (I3b). */
function wireTuiEntry(tuiDir: string): void {
  injectGoEntry({
    file: join(tuiDir, 'main.go'),
    goModPath: join(tuiDir, 'go.mod'),
    packageDir: 'plugin-glue',
    packageName: 'pluginglue',
    anchor: /^\s*RunE: func\(cmd \*cobra\.Command, args \[\]string\) error \{/,
    indent: '\t\t\t',
    body: [
      '// Generated plugin tabs. Constructed at startup so the glue is part of',
      "// the build; hand them to your Model when you add a tab strip.",
      'pluginTabs := pluginglue.Plugins()',
      '_ = pluginTabs',
    ],
  });
}

function generateAggregator(serverNames: string[], plugin: PluginInfo): string {
  return `// Plugin Glue index: ${plugin.name}
// Auto-generated by fragment connect — do not edit manually.

package pluginglue

import tea "github.com/charmbracelet/bubbletea"

// Tab is the contract every generated plugin tab satisfies. It is the stable
// surface main.go wires against, so adding or removing an MCP server never
// changes the entry point.
type Tab interface {
\tID() string
\tName() string
\tIcon() string
\tStart() tea.Cmd
\tStop()
\tView(width, height int) string
\tIsFocused() bool
\tSetFocused(focused bool)
}

// Plugins returns every generated plugin tab for ${plugin.name}.
func Plugins() []Tab {
\treturn []Tab{
${serverNames.map((n) => `\t\tNew${capitalize(n)}Plugin(),`).join('\n')}
\t}
}
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function generatePluginTab(serverName: string, plugin: PluginInfo): string {
  const structName = `${capitalize(serverName)}Plugin`;

  return `// Plugin Glue: ${serverName} from ${plugin.name}
// Auto-generated by fragment connect — do not edit manually.

package pluginglue

import (
\ttea "github.com/charmbracelet/bubbletea"
\t"github.com/charmbracelet/lipgloss"
)

// ${structName} is a TUI tab plugin for the ${serverName} MCP server.
type ${structName} struct {
\tfocused bool
}

func New${structName}() *${structName} {
\treturn &${structName}{}
}

func (p *${structName}) ID() string        { return "${serverName}" }
func (p *${structName}) Name() string      { return "${capitalize(serverName)}" }
func (p *${structName}) Icon() string      { return "◉" }
func (p *${structName}) IsFocused() bool   { return p.focused }
func (p *${structName}) SetFocused(f bool) { p.focused = f }

func (p *${structName}) Init(ctx interface{}) error { return nil }
func (p *${structName}) Start() tea.Cmd             { return nil }
func (p *${structName}) Stop()                      {}

func (p *${structName}) Update(msg tea.Msg) (*${structName}, tea.Cmd) {
\treturn p, nil
}

func (p *${structName}) View(width, height int) string {
\ttitle := lipgloss.NewStyle().
\t\tForeground(lipgloss.Color("#ff8c32")).
\t\tBold(true).
\t\tRender("${capitalize(serverName)} MCP Server")

\tdesc := lipgloss.NewStyle().
\t\tForeground(lipgloss.Color("#555")).
\t\tRender("Connected to ${plugin.name} plugin\\nServer: ${serverName}")

\treturn lipgloss.NewStyle().
\t\tWidth(width).
\t\tHeight(height).
\t\tPadding(1, 2).
\t\tRender(title + "\\n\\n" + desc)
}

func (p *${structName}) KeyHints() []struct{ Key, Help string } {
\treturn []struct{ Key, Help string }{
\t\t{Key: "r", Help: "refresh"},
\t}
}
`;
}
